include: lint_options.yaml
analyzer:
  exclude:
    - build/**
    - lib/l10n/intl/**
    - lib/**/generated/**
    - plugins/**
    - android/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    invalid_annotation_target: ignore
