services:
  flclash:
    image: ghcr.io/pickrui/flclash:latest
    container_name: flclash
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - NO_WEBCAM=true
    ports:
      - "3000:3000"
      - "3001:3001"
    expose:
      - "7890"
    volumes:
      - flclash-config:/config
    shm_size: "1gb"
    restart: unless-stopped

volumes:
  flclash-config:
